version: 2
jobs:
  prepare:
    docker:
      - image: mbedos/mbed-os-env:stable
    working_directory: ~
    steps:
      - checkout:
          path: mbed-os-bluetooth-integration-testsuite
      - run: |
          cd mbed-os-bluetooth-integration-testsuite
          cd ble-cliapp
          mbed deploy
      - persist_to_workspace:
          root: /root/project
          paths: mbed-os-bluetooth-integration-testsuite

  build_nrf52840:
    docker:
      - image: mbedos/mbed-os-env:stable
    working_directory: ~
    steps:
      - attach_workspace:
          at: /root/project
      - run: |
          cd mbed-os-bluetooth-integration-testsuite
          cd ble-cliapp
          mbed compile -t GCC_ARM -m NRF52840_DK || exit 1

  build_disco_l475vg:
    docker:
      - image: mbedos/mbed-os-env:stable
    working_directory: ~
    steps:
      - attach_workspace:
          at: /root/project
      - run: |
          cd mbed-os-bluetooth-integration-testsuite
          cd ble-cliapp
          mbed compile -t GCC_ARM -m DISCO_L475VG_IOT01A || exit 1

workflows:
  version: 2
  workflow:
    jobs:
    - prepare
    - build_nrf52840:
        requires:
          - prepare
    - build_disco_l475vg:
        requires:
          - prepare
