name: Build tests
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * 0'
  pull_request:
jobs:
  build-integration-tests:
    name: Build cli-app
    runs-on: ubuntu-latest
    container: mbedos/mbed-os-env:latest
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y lavacli curl

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build NRF cli-app
        run: |
          cd ble-cliapp
          mbed deploy
          mbed compile -t GCC_ARM -m NRF52840_DK --profile toolchains_profile.json || exit 1

      - name: Uploading Binaries
        uses: actions/upload-artifact@v2
        with:
          name: ble-cliapp-GCC_ARM-NRF52840_DK-${{ github.event.pull_request.head.sha || github.sha }}
          path: ble-cliapp/BUILD/NRF52840_DK/GCC_ARM-TOOLCHAINS_PROFILE/ble-cliapp.hex
          if-no-files-found: error

      - name: Build DISCO cli-app
        run: |
          cd ble-cliapp
          mbed compile -t GCC_ARM -m DISCO_L475VG_IOT01A --profile toolchains_profile.json || exit 1

      - name: Uploading Binaries
        uses: actions/upload-artifact@v2
        with:
          name: ble-cliapp-GCC_ARM-DISCO_L475VG_IOT01A-${{ github.event.pull_request.head.sha || github.sha }}
          path: ble-cliapp/BUILD/DISCO_L475VG_IOT01A/GCC_ARM-TOOLCHAINS_PROFILE/ble-cliapp.bin
          if-no-files-found: error

      - name: Trigger lava workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Run integration tests
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.PAT }}
          inputs: '{ "SHA": "${{ github.event.pull_request.head.sha || github.sha }}" }'
